### ISSUE TITLE
no time update on the matrix

### ISSUE THREAD

**Issue by valbuz** [3KUdelta/MDparola_MQTT_monitor#2]
Why doesn't updating the time on the display....?

**Comment by 3KUdelta** [comment]
Hmm, very difficult to judge. Maybe you can provide more information? 
- Serial Monitor output would be a good start.

**Comment by valbuz** [comment]
After start, the time is displayed on the matrix. but it remain with the same digit's.
in the serial monitor, i see the updates time...
which routine updates the time on the matrix? only after 24hour?

**Comment by 3KUdelta** [comment]
No, the time shows every minute. 
- The time is defined in Zone 1
- in setup() its defined as 
`P.displayZoneText(1, actualtime, PA_CENTER, SPEED_TIME, PAUSE_TIME, PA_PRINT, PA_NO_EFFECT);`
- in loop() it is called ` P.displayReset(1);`

You can try to copy the P.displayZoneText(1,... just before the `P.displayReset(1);`

**Comment by valbuz** [comment]
it works!

thanks
